wallpaper {
  monitor = DP-2
  path = /home/arcoss/Documents/wallpapers/minimal_landscape.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/arcoss/Documents/wallpapers/minimal_landscape.jpg
  fit_mode = cover
}

# fallback (optionnel) si un nouvel écran apparaît
wallpaper {
  monitor =
  path = /home/arcoss/Documents/wallpapers/minimal_landscape.jpg
  fit_mode = cover
}

splash = false
